config/routes.rb
Rails.application.routes.draw do

  root 'monsters#home'

  resources :users do
    resources :messages
    resources :favorites
  end
  get '/user-monsters', to: 'users#list_monsters'

  resources :monsters do
    resources :comments
    resources :vote
    get :add_favorite, on: :member
  end

  # administrator
  get '/administrator', to: 'administrator#index'

  # auth
  get '/auth_site',     to: 'users#auth' # Локальная форма авторизации

  # search result page
  post '/search',       to: 'monsters#search'

  # Сессии
  post '/auth_social',              to: 'sessions#create' # Создание сессии с помощью соц.сетей
  post '/auth_local',               to: 'sessions#create_via_password' # Создание сессии с помощью пароля
  get '/sessions/signout',          to: 'sessions#sign_out'
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/auth/failure',            to: 'sessions#failure', via: [:get, :post]

end

app/models/monster.rb
# Монстры
class Monster < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  accepts_nested_attributes_for :comments
  def self.name_starts_with(letter)
    where('UPPER(name) LIKE UPPER(?)', "#{letter}%")
  end

  def self.letter(letter)
    name_starts_with(letter).by_name
  end

  def self.letterize(letter)
    letter =~ /\A[A-Za-z]\z/ ? letter.upcase : 'A'
  end

  def self.by_name
    order(name: :asc)
  end

  # Validations
  validates :name, presence: true
  validates :level, numericality: true
  validates :hp, numericality: true
  validates :exp, numericality: true
  validates :jexp, numericality: true
  validates :atk1, numericality: true
  validates :atk2, numericality: true
  validates :def, numericality: true
  validates :mdef, numericality: true
  validates :str, numericality: true
  validates :agi, numericality: true
  validates :vit, numericality: true
  validates :int, numericality: true
  validates :dex, numericality: true
  validates :luk, numericality: true
  validates :scale, numericality: true
  validates :race, numericality: true
  validates :element, numericality: true
end

app/controllers/monsters_controller.rb
# Monsters
class
  MonstersController < ApplicationController

  load_and_authorize_resource
  skip_authorize_resource only: [:home, :search]

  # Вывод всех монстров
  def index
    authorize! :index, Monster
    @letter   = Monster.letterize(params[:letter])
    @monsters = Monster.letter(@letter).page(params[:page]).per(20)
  end

  # Страница результатов поиска монстров
  def search
    search_monsters =
      Monster.where(
        name: params[:search][:name]
      )
    @monsters       = search_monsters.page(1).per(10)
  end

  # Страница описания монстра
  def show
    authorize! :read, @monster
    @monster = Monster.find(params[:id])
  end

  # Форма создания нового монстра
  def new
    authorize! :new, Monster
    @monster = Monster.new
  end

  # Редактирование монстра
  def edit
    @monster = Monster.find(params[:id])
    if check_own?(@monster.own)
      respond_to :html
    else
      redirect_to :back,
                  flash: {
                    error: 'Недостаточно прав для редактирования записи'
                  }
    end
  end

  # Обновление монстра
  def update
    monster = Monster.update(monster_params)
    respond_to do |format|
      if monster.update(monster_params)
        format.html redirect_to monster, notice: 'Монстр обновлен.'
        format.json render :show, status: :ok, location: monster
      end
    end
  end

  private

  # Проверка владельца монстра
  def check_monster_owner?(id)
    @current_user.id == id
  end

  # Обновления счетчика избранных монстров
  def fix_count
    user           = User.find(current_user.id)
    user.fav_count = user.fav_count + 1
    user.save
  end

  def monster_params
    params.require(:monster).permit(:name, :hp, :def, :mdef, :str, :agi,
                                    :vit, :int, :dex, :luk, :scale)
  end

  def comment_params
    params.require(:monster).permit(:content)
  end
end

app/views/monsters/edit.slim
.container
  .col-md-12.well-page
    .col-md-12
      .title
        h1 Редактирование монстра #{@monster.name}
    .col-md-12
      = simple_form_for :monster, :url => { :action => "create" }, html: { multipart: true } do |f|
        .form-inputs
          .col-md-6
            = f.input :name, required: true, autofocus: true
            = f.input :level, required: true, autofocus: true
            = f.input :hp, required: true, autofocus: true
            = f.input :exp, required: true, autofocus: true
            = f.input :jexp, required: true, autofocus: true
            = f.input :atk1, required: true, autofocus: true
            = f.input :atk2, required: true, autofocus: true
            = f.input :def, required: true, autofocus: true
            = f.input :mdef, required: true, autofocus: true
          .col-md-6
            = f.input :str, required: true, autofocus: true
            = f.input :agi, required: true, autofocus: true
            = f.input :vit, required: true, autofocus: true
            = f.input :int, required: true, autofocus: true
            = f.input :dex, required: true, autofocus: true
            = f.input :luk, required: true, autofocus: true
            = f.input :scale, required: true, autofocus: true
            = f.input :race, required: true, autofocus: true
            = f.input :element, required: true, autofocus: true
        .form-actions
          = f.button :submit, "Сохранить", :class => "btn btn-raised btn-warning"

app/views/monsters/home.slim
.home-well
  .container
    .col-md-offset-2.col-md-8.col-md-offset-2
      .home-search
        = simple_form_for :search, :url => { :controller => "monsters", :action => "search" }, html: { multipart: true, class: '', :method => :post } do |f|
          .form-group.is-empty
            = f.input :name, required: true, autofocus: true, :class => "form-control col-md-8", placeholder: 'Поиск', label:false
        

app/views/monsters/index.slim
.container.content
  .monster-nav-links
    .row
      a.monster-nav-link href="/monsters?letter=A"  A
      a.monster-nav-link href="/monsters?letter=B"  B
      a.monster-nav-link href="/monsters?letter=C"  C
      a.monster-nav-link href="/monsters?letter=D"  D
      a.monster-nav-link href="/monsters?letter=E"  E
      a.monster-nav-link href="/monsters?letter=F"  F
      a.monster-nav-link href="/monsters?letter=G"  G
      a.monster-nav-link href="/monsters?letter=H"  H
      a.monster-nav-link href="/monsters?letter=I"  I
      a.monster-nav-link href="/monsters?letter=J"  J
      a.monster-nav-link href="/monsters?letter=K"  K
      a.monster-nav-link href="/monsters?letter=L"  L
      a.monster-nav-link href="/monsters?letter=M"  M
      a.monster-nav-link href="/monsters?letter=N"  N
      a.monster-nav-link href="/monsters?letter=O"  O
      a.monster-nav-link href="/monsters?letter=P"  P
      a.monster-nav-link href="/monsters?letter=Q"  Q
      a.monster-nav-link href="/monsters?letter=R"  R
      a.monster-nav-link href="/monsters?letter=S"  S
      a.monster-nav-link href="/monsters?letter=T"  T
      a.monster-nav-link href="/monsters?letter=U"  U
      a.monster-nav-link href="/monsters?letter=V"  V
      a.monster-nav-link href="/monsters?letter=W"  W
      a.monster-nav-link href="/monsters?letter=X"  X
      a.monster-nav-link href="/monsters?letter=Y"  Y
      a.monster-nav-link href="/monsters?letter=Z"  Z
  - if can? :manage, Monster
    | Hello
  .row  
    - @monsters.each do |monster|
      .col-md-12.databox
        .col-md-6
          .row
            .title 
              = link_to monster.name, monster
        .col-md-6
          .row    
            p.buttons.text-right
              = link_to new_monster_vote_path(monster), remote: true, class: "add-like" do
                = content_tag(:i, "", :class=>'fa fa-heart-o')
    .text-center
      = paginate @monsters, :theme => 'twitter-bootstrap-3'

app/views/monsters/new.slim
.container
  .col-md-12.well-page
    .col-md-12
      .title
        h1 Новый монстр
    .col-md-12
      = simple_form_for :monster, :url => { :action => "create" }, html: { multipart: true } do |f|
        - if @monster.errors.any?
          #error_explanation
            h2
              = pluralize(@monster.errors.count, "error")
              | prohibited this article from being saved:
            ul
              - @monster.errors.full_messages.each do |msg|
                li= msg
        .form-inputs
          .col-md-6
            = f.input :name, required: true, autofocus: true
            = f.input :level, required: true, autofocus: true
            = f.input :hp, required: true, autofocus: true
            = f.input :exp, required: true, autofocus: true
            = f.input :jexp, required: true, autofocus: true
            = f.input :atk1, required: true, autofocus: true
            = f.input :atk2, required: true, autofocus: true
            = f.input :def, required: true, autofocus: true
            = f.input :mdef, required: true, autofocus: true
          .col-md-6
            = f.input :str, required: true, autofocus: true
            = f.input :agi, required: true, autofocus: true
            = f.input :vit, required: true, autofocus: true
            = f.input :int, required: true, autofocus: true
            = f.input :dex, required: true, autofocus: true
            = f.input :luk, required: true, autofocus: true
            = f.input :scale, required: true, autofocus: true
            = f.input :race, required: true, autofocus: true
            = f.input :element, required: true, autofocus: true
        .form-actions
          = f.button :submit, "Добавить", :class => "btn btn-raised btn-warning"

app/views/monsters/search.slim
.container.content
  .row  
    - @monsters.each do |monster|
      .col-md-12.databox
        .col-md-6
          .row
            .title 
              = link_to monster.name, monster
        .col-md-6
          .row    
            p.buttons.text-right
              - if @current_user.id == monster.own
                span
                  = link_to add_favorite_monster_path(monster), remote: true, class: "add-favorite" do
                    = content_tag(:i, "", :class=>'fa fa-user-circle')
              span  
                = link_to like_monster_path(monster), remote: true, class: "add-like" do
                  - if check_like(monster)
                    = content_tag(:i, "", :class=>'fa fa-thumbs-up')
                  - else
                    = content_tag(:i, "", :class=>'fa fa-thumbs-o-up')
                span.count
                  = monster.like
              span  
                = link_to dislike_monster_path(monster), class: "add-dislike" do
                  - if check_like(monster)
                    = content_tag(:i, "", :class=>'fa fa-thumbs-up')
                  - else
                    = content_tag(:i, "", :class=>'fa fa-thumbs-o-up')
                span.count
                  = monster.dislike
              span
                = link_to add_favorite_monster_path(monster), remote: true, class: "add-favorite" do
                  - if check_favorite(monster.id)
                    = content_tag(:i, "", :class=>'fa fa-heart')
                  - else
                    = content_tag(:i, "", :class=>'fa fa-heart-o')
              span
                = link_to edit_monster_path(monster) do
                  = content_tag(:i, "", :class=>'fa fa-pencil-square-o')
    .text-center
      = paginate @monsters, :theme => 'twitter-bootstrap-3'

app/views/monsters/show.slim
.container(ng-app="single-page-mod")
  .col-md-12.well-page
    .col-md-12
      .title
        h1 #{@monster.name}
    .col-md-12.text-center
      img src="http://rurowiki.ru/media/monsters/#{1000 + @monster.id.to_i}.gif"
      h2 Характеристики  
    .col-md-6
      table.table.table-striped
        tbody
          tr
            td lvl: #{@monster.name}
          tr
            td lvl: #{@monster.level}
          tr
            td hp: #{@monster.hp}
          tr
            td exp: #{@monster.exp}
          tr
            td def: #{@monster.jexp}
          tr
            td mdef: #{@monster.atk1}
          tr
            td str: #{@monster.atk2}
          tr
            td agi: #{@monster.def}
          tr
            td vit: #{@monster.mdef}
    .col-md-6
      table.table.table-striped
        tbody
          tr
            td lvl: #{@monster.str}
          tr
            td hp: #{@monster.agi}
          tr
            td exp: #{@monster.vit}
          tr
            td def: #{@monster.int}
          tr
            td mdef: #{@monster.dex}
          tr
            td str: #{@monster.luk}
          tr
            td agi: #{@monster.scale}
          tr
            td vit: #{@monster.race}
          tr
            td int: #{@monster.element}
    .col-md-12
  .col-md-12.well-page(ng-controller="CommentsCtrl")
    .col-md-12
      .title
        h2 Комментарии
      .col-md-12
        .row
          - if @current_user
            = simple_form_for ([@monster, @monster.comments.build]) do |f|
              = f.input :text, placeholder: "Новый комментарий", input_html: { "ng-keyup" => "word_count()", "ng-init" => "comment_words_count=0" } 
              .count-words
                | Колличество символов: {{comment_words_count}}
              = f.button :submit, :class => "btn btn-raised btn-warning"
          - else
            .text-center
              = link_to "Зарегистрируйтесь чтобы оставить комментарий", new_user_path, :class => "btn btn-raised btn-warning"
      - @monster.comments.each do |comment|
        - if comment.text
          .col-md-12.comment
            .row
              .title-comment
                h3
                  = comment.title
              p 
                = comment.text
              p 
                | удалить